# Generated by Django 5.0.1 on 2024-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='pid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='pimg',
            field=models.ImageField(upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
