# Generated by Django 5.0.1 on 2024-05-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_catagory_category_rename_pid_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname',
        ),
    ]
